"""More hand-written document topics (5 sections × 3 points each)."""

MORE_DOC_TOPICS = {
    "The French Revolution": [
        ("Background", ["France faced heavy debt and food shortages in the 1780s", "Society was split into three estates with unequal taxes", "Enlightenment ideas questioned royal power"]),
        ("1789", ["The Estates-General met in May 1789", "The Third Estate formed the National Assembly", "The Bastille was stormed on 14 July 1789"]),
        ("Radical phase", ["The monarchy was abolished in 1792", "Louis XVI was executed in 1793", "The Reign of Terror killed thousands of suspected enemies"]),
        ("Napoleon", ["Napoleon Bonaparte took power in 1799", "He crowned himself emperor in 1804", "The Napoleonic Code reshaped French law"]),
        ("Legacy", ["Spread ideas of liberty, equality and citizenship", "Weakened absolute monarchy across Europe", "Inspired later democratic movements"]),
    ],
    "Photosynthesis": [
        ("Overview", ["Plants turn light energy into chemical energy", "It takes place in chloroplasts", "Oxygen is released as a by-product"]),
        ("Inputs", ["Carbon dioxide from the air", "Water from the soil", "Sunlight absorbed by chlorophyll"]),
        ("Light reactions", ["Happen in the thylakoid membranes", "Split water and release oxygen", "Produce ATP and NADPH"]),
        ("Calvin cycle", ["Happens in the stroma", "Uses ATP and NADPH to fix carbon dioxide", "Produces sugars such as glucose"]),
        ("Why it matters", ["Supplies the oxygen we breathe", "Forms the base of most food chains", "Removes carbon dioxide from the atmosphere"]),
    ],
    "Personal finance basics": [
        ("Budgeting", ["Track income and expenses every month", "A common guide is the 50/30/20 rule", "Needs first, then wants, then savings"]),
        ("Emergency fund", ["Aim for 3 to 6 months of expenses", "Keep it in a safe, easy-to-access account", "Only use it for real emergencies"]),
        ("Debt", ["Pay off high-interest debt first", "Pay credit card bills in full", "Avoid borrowing for things that lose value"]),
        ("Investing", ["Start early to benefit from compounding", "Diversify across different assets", "Low-cost index funds suit many beginners"]),
        ("Good habits", ["Automate savings on payday", "Review your goals every year", "Protect yourself with insurance"]),
    ],
    "Cybersecurity for beginners": [
        ("Why it matters", ["Personal data is valuable to criminals", "Most attacks target common mistakes", "Simple habits block most threats"]),
        ("Passwords", ["Use a long, unique password for each account", "A password manager makes this easy", "Turn on two-factor authentication"]),
        ("Phishing", ["Be wary of urgent messages asking for details", "Check the sender and the link address", "Never share one-time passwords"]),
        ("Devices", ["Install updates promptly", "Only install apps from trusted stores", "Lock your phone with a PIN or biometrics"]),
        ("Backups", ["Back up important files regularly", "Keep at least one backup offline", "Test that you can restore it"]),
    ],
    "The Indian freedom struggle": [
        ("Early resistance", ["The 1857 uprising challenged East India Company rule", "Afterward the British Crown took direct control", "The Indian National Congress formed in 1885"]),
        ("Gandhi's movements", ["Non-Cooperation Movement in 1920", "Salt March in 1930", "Quit India Movement in 1942"]),
        ("Key leaders", ["Mahatma Gandhi led non-violent resistance", "Jawaharlal Nehru and Sardar Patel shaped the movement", "Subhas Chandra Bose led the Indian National Army"]),
        ("Independence", ["India became independent on 15 August 1947", "The subcontinent was partitioned into India and Pakistan", "Partition caused mass migration and violence"]),
        ("Legacy", ["The Constitution came into force on 26 January 1950", "Inspired anti-colonial movements worldwide", "Showed the power of mass non-violent protest"]),
    ],
    "Electric vehicles": [
        ("How they work", ["A battery powers an electric motor", "No tailpipe emissions while driving", "Regenerative braking recovers energy"]),
        ("Benefits", ["Lower running and maintenance costs", "Quiet and smooth to drive", "Cleaner air in cities"]),
        ("Charging", ["Home charging overnight suits most daily use", "Fast chargers add significant range in under an hour", "Public charging networks are growing"]),
        ("Challenges", ["Higher upfront prices than many petrol cars", "Charging can take longer than refuelling", "Battery production needs mined materials"]),
        ("The future", ["Battery costs keep falling", "More models in every price range", "Batteries can be recycled and reused"]),
    ],
    "Machine learning basics": [
        ("What it is", ["Computers learn patterns from data", "Instead of being programmed with explicit rules", "Predictions improve with more and better data"]),
        ("Types", ["Supervised learning uses labelled examples", "Unsupervised learning finds structure in unlabelled data", "Reinforcement learning learns from rewards"]),
        ("Workflow", ["Collect and clean data", "Train a model and evaluate it on held-out data", "Deploy it and monitor performance"]),
        ("Common models", ["Linear and logistic regression", "Decision trees and random forests", "Neural networks for images, text and audio"]),
        ("Pitfalls", ["Overfitting to the training data", "Bias in the data leads to biased results", "Always test on data the model hasn't seen"]),
    ],
    "The human brain": [
        ("Overview", ["About 86 billion neurons", "Uses roughly 20% of the body's energy", "Protected by the skull and cerebrospinal fluid"]),
        ("Main parts", ["Cerebrum: thinking, senses and movement", "Cerebellum: balance and coordination", "Brainstem: breathing and heart rate"]),
        ("Neurons", ["Communicate with electrical and chemical signals", "Connect at synapses", "Connections strengthen with use"]),
        ("Learning and memory", ["The hippocampus helps form new memories", "Sleep helps consolidate what we learn", "Practice builds stronger pathways"]),
        ("Brain health", ["Regular exercise and good sleep", "A balanced diet and staying social", "Protect your head from injury"]),
    ],
    "World War II overview": [
        ("Causes", ["Aftermath of World War I and the Treaty of Versailles", "Rise of fascism in Germany, Italy and Japan", "Germany invaded Poland in September 1939"]),
        ("Major fronts", ["Europe and the Eastern Front", "North Africa and the Mediterranean", "The Pacific war with Japan"]),
        ("Turning points", ["Battle of Stalingrad, 1942–43", "Battle of Midway, 1942", "D-Day landings in Normandy, June 1944"]),
        ("End of the war", ["Germany surrendered in May 1945", "Atomic bombs were dropped on Hiroshima and Nagasaki in August 1945", "Japan surrendered in September 1945"]),
        ("Aftermath", ["Tens of millions of people died", "The United Nations was founded in 1945", "The Cold War began between the US and the USSR"]),
    ],
    "Learning a new language": [
        ("Set goals", ["Decide why you're learning", "Set small weekly targets", "Track your progress"]),
        ("Daily practice", ["Study a little every day instead of cramming", "Use spaced-repetition flashcards for vocabulary", "Learn the most common words first"]),
        ("Listening and speaking", ["Listen to podcasts and music in the language", "Shadow native speakers out loud", "Find a conversation partner"]),
        ("Reading and writing", ["Start with graded readers or children's books", "Keep a short daily journal", "Read about topics you enjoy"]),
        ("Stay motivated", ["Mistakes are part of learning", "Celebrate milestones", "Immerse yourself with films and shows"]),
    ],
    "Public speaking tips": [
        ("Prepare", ["Know your audience and your main message", "Structure: opening, three key points, close", "Practise out loud several times"]),
        ("Start strong", ["Open with a question, story or surprising fact", "Tell the audience what they'll gain", "Smile and make eye contact"]),
        ("Delivery", ["Speak slowly and pause for emphasis", "Use gestures naturally", "Vary your tone to keep interest"]),
        ("Visuals", ["Keep slides simple with few words", "One idea per slide", "Use images and charts to explain"]),
        ("Handling nerves", ["Breathe slowly before you start", "Focus on helping the audience", "Nerves fade as you get going"]),
    ],
    "The Moon": [
        ("Basics", ["Earth's only natural satellite", "About 384,400 km from Earth", "Roughly a quarter of Earth's diameter"]),
        ("Formation", ["Likely formed about 4.5 billion years ago", "Probably from a giant impact with Earth", "Its surface is covered in craters"]),
        ("Phases", ["We see different parts lit by the Sun", "A full cycle takes about 29.5 days", "The same side always faces Earth"]),
        ("Effects on Earth", ["Its gravity causes ocean tides", "It stabilizes Earth's tilt", "It causes solar and lunar eclipses"]),
        ("Exploration", ["Apollo 11 landed humans on the Moon in 1969", "Twelve astronauts walked on it", "India's Chandrayaan-3 landed near the south pole in 2023"]),
    ],
    "Yoga for beginners": [
        ("What yoga is", ["A practice combining postures, breathing and focus", "Originated in ancient India", "Improves flexibility, strength and calm"]),
        ("Getting started", ["Use a non-slip mat and comfortable clothes", "Practise on an empty stomach", "Start with 15–20 minutes"]),
        ("Beginner poses", ["Mountain pose (Tadasana)", "Downward dog (Adho Mukha Svanasana)", "Child's pose (Balasana)"]),
        ("Breathing", ["Breathe slowly through the nose", "Try alternate nostril breathing", "Let the breath guide your movement"]),
        ("Safety", ["Never push into pain", "Modify poses as needed", "Check with a doctor if you have injuries"]),
    ],
    "Cloud computing": [
        ("What it is", ["Renting computing resources over the internet", "Pay only for what you use", "Run by providers such as AWS, Azure and Google Cloud"]),
        ("Service models", ["IaaS: virtual machines and storage", "PaaS: platforms to run your code", "SaaS: ready-to-use apps like email"]),
        ("Benefits", ["Scale up or down quickly", "No upfront hardware costs", "Global reach and reliability"]),
        ("Challenges", ["Costs can grow if not monitored", "Security is a shared responsibility", "Depends on internet connectivity"]),
        ("Getting started", ["Use free tiers to experiment", "Learn core services like compute and storage", "Set budgets and alerts"]),
    ],
    "Ocean conservation": [
        ("Why oceans matter", ["Cover about 71% of Earth's surface", "Produce much of the oxygen we breathe", "Feed billions of people"]),
        ("Threats", ["Plastic pollution", "Overfishing", "Warming and acidification from climate change"]),
        ("Coral reefs", ["Home to about a quarter of marine species", "Bleaching happens when water gets too warm", "Many reefs are at risk"]),
        ("Solutions", ["Marine protected areas", "Sustainable fishing rules", "Cutting plastic waste"]),
        ("What you can do", ["Use less single-use plastic", "Choose sustainable seafood", "Join beach clean-ups"]),
    ],
    "Effective study techniques": [
        ("Active recall", ["Test yourself instead of rereading", "Use flashcards and practice questions", "Explain topics from memory"]),
        ("Spaced repetition", ["Review material over increasing intervals", "Short sessions beat cramming", "Apps can schedule reviews for you"]),
        ("Focus", ["Remove distractions like your phone", "Study in 25–50 minute blocks", "Take short breaks between blocks"]),
        ("Understanding", ["Connect new ideas to what you know", "Use diagrams and summaries", "Teach the topic to someone else"]),
        ("Health", ["Sleep well, especially before exams", "Exercise boosts concentration", "Eat regular, balanced meals"]),
    ],
}
MORE_HELD_OUT_DOC_TOPICS = {
    "The Roman Empire": [
        ("Origins", ["Rome grew from a small city on the Tiber", "It became a republic around 509 BC", "Augustus became the first emperor in 27 BC"]),
        ("Height of power", ["Stretched from Britain to the Middle East", "The Pax Romana brought two centuries of relative peace", "Linked by roads, trade and a common law"]),
        ("Achievements", ["Aqueducts, roads and concrete buildings", "Latin shaped many modern languages", "Roman law influenced later legal systems"]),
        ("Decline", ["Political instability and economic troubles", "Pressure from groups on its borders", "The Western Empire fell in AD 476"]),
        ("Legacy", ["The Eastern Empire lasted until 1453", "Influenced government, architecture and language", "Many cities still follow Roman street plans"]),
    ],
}
