"""More hand-written direct answers, clarifying questions and unsupported
requests (no tool needed for any of these)."""

MORE_QA = [
    (["what is gravity", "explain gravity simply"], "**Gravity** is the force that pulls objects with mass toward each other. It keeps us on the ground, makes things fall, holds the Moon in orbit around Earth and Earth around the Sun.\n\nThe more massive an object and the closer you are, the stronger its pull. On Earth, falling objects speed up by about **9.8 m/s every second**."),
    (["what is DNA", "explain dna"], "**DNA** (deoxyribonucleic acid) is the molecule that carries the instructions for building and running living things.\n\n- It's shaped like a twisted ladder, the **double helix**.\n- The rungs are pairs of four bases: **A–T** and **C–G**.\n- The order of the bases encodes **genes**, which tell cells how to make proteins.\n\nAlmost every cell in your body has a full copy of your DNA."),
    (["how does the internet work in simple words", "explain the internet simply"], "The internet is a giant network of computers that send each other data in small **packets**.\n\n1. When you open a website, your device asks a **DNS** server for the site's address (its IP).\n2. Your request travels through **routers** across cables, fiber and sometimes satellites.\n3. The website's **server** sends back the page in packets.\n4. Your browser puts the packets back together and shows the page.\n\nAll of this usually takes less than a second."),
    (["what is inflation", "explain inflation"], "**Inflation** is the general rise in prices over time, which means the same money buys less.\n\nFor example, with 5% inflation, something that costs ₹100 today costs about ₹105 next year. A little inflation is normal; central banks usually aim for around **2–4%**. High inflation hurts savings, so people invest to keep their money's value."),
    (["what's the difference between weather and climate", "weather vs climate"], "**Weather** is what the atmosphere is doing right now or over a few days: rain today, 30 °C tomorrow.\n\n**Climate** is the average weather of a place over a long time, usually 30 years or more: \"Chennai is hot and humid\".\n\nA simple way to remember it: *climate is what you expect, weather is what you get.*"),
    (["how do vaccines work", "explain vaccines"], "Vaccines train your immune system to recognise a germ **before** you meet the real thing.\n\n1. A vaccine contains a harmless piece or weakened form of a virus or bacterium, or instructions to make one of its proteins.\n2. Your immune system responds and makes **antibodies** and **memory cells**.\n3. If you're exposed later, your body recognises the germ and fights it off quickly.\n\nThat's why vaccinated people are much less likely to get seriously ill."),
    (["what is a black hole", "explain black holes"], "A **black hole** is a region of space where gravity is so strong that nothing, not even light, can escape.\n\n- It forms when a very massive star collapses at the end of its life.\n- Its boundary is the **event horizon**, the point of no return.\n- Supermassive black holes, millions of times the Sun's mass, sit at the centres of most galaxies."),
    (["how do I center a div", "center a div css"], "The easiest modern way is **flexbox** on the parent:\n\n```css\n.parent {\n  display: flex;\n  justify-content: center; /* horizontal */\n  align-items: center;     /* vertical */\n  min-height: 100vh;\n}\n```\n\nOr with **grid**: `display: grid; place-items: center;`."),
    (["what is git", "explain git"], "**Git** is a version control system: it tracks changes to your files so you can go back in time, work on features separately, and collaborate.\n\nThe basics:\n\n```bash\ngit init                 # start tracking a folder\ngit add .                # stage your changes\ngit commit -m \"message\"  # save a snapshot\ngit log                  # see history\n```\n\n**GitHub** is a website that hosts Git repositories online."),
    (["what is the difference between RAM and storage", "ram vs storage"], "**RAM** is your device's short-term working memory; **storage** is long-term memory.\n\n| | RAM | Storage (SSD/flash) |\n|---|---|---|\n| Purpose | Running apps right now | Keeping files and apps |\n| Speed | Very fast | Slower |\n| When power is off | Cleared | Kept |\n| Typical phone size | 6–16 GB | 128 GB–1 TB |\n\nMore RAM lets you run more apps smoothly; more storage lets you keep more photos and files."),
    (["give me a healthy breakfast idea", "healthy breakfast ideas"], "Here are some quick, healthy breakfasts:\n\n- **Oats** cooked with milk, topped with banana and nuts\n- **Idli or dosa** with sambar for protein and fibre\n- **Vegetable poha or upma** with peanuts\n- **Greek yogurt** with fruit and seeds\n- **Eggs** (boiled or an omelette) with whole-grain toast\n\nAim for some protein and fibre to stay full until lunch."),
    (["how do I stay motivated", "tips to stay motivated"], "A few things that really help:\n\n1. **Make goals small and specific**: \"study 30 minutes\" beats \"study more\".\n2. **Start before you feel ready**: motivation often comes after you begin.\n3. **Track progress**: a simple streak calendar works well.\n4. **Remove friction**: prepare things the night before.\n5. **Reward yourself** after finishing, not before.\n\nOn hard days, aim to just show up; consistency matters more than intensity."),
    (["what is the speed of light", "how fast is light"], "Light travels at about **299,792 km per second** in a vacuum, roughly 300,000 km/s. That's fast enough to circle Earth about 7.5 times in one second. Sunlight takes about **8 minutes 20 seconds** to reach us."),
    (["what is an algorithm", "explain algorithms"], "An **algorithm** is a step-by-step set of instructions for solving a problem.\n\nA recipe is an everyday example. In programming, algorithms do things like:\n\n- **Sorting** a list (e.g. merge sort)\n- **Searching** for an item (e.g. binary search)\n- **Finding routes** on a map (e.g. Dijkstra's algorithm)\n\nGood algorithms are correct, efficient and clear."),
    (["what's the tallest mountain in the world", "tallest mountain"], "**Mount Everest** is the tallest mountain above sea level, at **8,849 m (29,032 ft)**, on the border of Nepal and China. Measured from base to peak, Hawaii's Mauna Kea is taller, but most of it is under the ocean."),
    (["what does CPU mean", "what is a cpu"], "**CPU** stands for **Central Processing Unit**, the \"brain\" of a computer or phone. It runs the instructions of every app.\n\nKey specs:\n- **Cores**: more cores can do more tasks at once\n- **Clock speed** (GHz): how many cycles per second\n- **Cache**: small, very fast memory on the chip"),
    (["how much water should I drink a day", "daily water intake"], "A common guideline is about **2–3 litres a day** for most adults, including water from food and other drinks. You need more in hot weather, when exercising, or if you're pregnant or breastfeeding.\n\nA simple check: if you're rarely thirsty and your urine is pale yellow, you're probably drinking enough."),
    (["write a haiku about rain", "haiku about the rain"], "**Rain**\n\nSoft drops on the roof,\nthe whole street hums a slow song,\npuddles hold the sky."),
    (["tell me a fun fact", "give me a random fun fact"], "Here's one: **octopuses have three hearts and blue blood.** Two hearts pump blood to the gills and one to the rest of the body, and their blood uses copper-based hemocyanin instead of iron, which makes it blue."),
    (["what is a noun", "explain nouns"], "A **noun** is a word that names a person, place, thing or idea.\n\n- Person: *teacher, Priya*\n- Place: *city, Chennai*\n- Thing: *phone, book*\n- Idea: *happiness, freedom*\n\nNouns can be **common** (*city*) or **proper** (*Chennai*, always capitalised)."),
    (["convert 5 km to miles", "5 kilometers in miles"], "**5 km ≈ 3.11 miles.**\n\n1 km = 0.621 miles, so 5 × 0.621 = 3.11."),
    (["what is 12 times 8", "12 x 8"], "**12 × 8 = 96.**"),
    (["what is the square root of 144", "sqrt 144"], "The square root of 144 is **12**, because 12 × 12 = 144."),
    (["how many continents are there", "list the continents"], "There are **7 continents**:\n\n1. Asia\n2. Africa\n3. North America\n4. South America\n5. Antarctica\n6. Europe\n7. Australia (Oceania)\n\nAsia is the largest and Australia the smallest."),
    (["what is the pythagorean theorem", "explain pythagoras theorem"], "In a right-angled triangle, the square of the longest side (the **hypotenuse**) equals the sum of the squares of the other two sides:\n\n**a² + b² = c²**\n\nExample: if the two shorter sides are 3 and 4, then c² = 9 + 16 = 25, so **c = 5**."),
    (["explain object oriented programming", "what is oop"], "**Object-oriented programming (OOP)** organises code around **objects** that bundle data and the functions that work on it.\n\nFour key ideas:\n1. **Encapsulation**: keep data and methods together and hide internal details.\n2. **Inheritance**: a class can reuse and extend another (a `Dog` is an `Animal`).\n3. **Polymorphism**: different classes can share the same interface.\n4. **Abstraction**: expose only what's needed.\n\n```python\nclass Animal:\n    def speak(self):\n        return \"...\"\n\nclass Dog(Animal):\n    def speak(self):\n        return \"Woof!\"\n```"),
    (["good morning", "gm"], "Good morning! ☀️ How can I help you today?"),
    (["good night", "gn"], "Good night! 🌙 Sleep well, and I'm here whenever you need me."),
    (["you're awesome", "great job"], "Thank you! 😊 Happy to help. What's next?"),
    (["what's your name", "who made you"], "I'm **Mnx**, your AI assistant, running right here on your device."),
]

# Vague requests: ask one short clarifying question (no tool).
CLARIFY = [
    (["make a presentation", "create slides", "I need a ppt"], "Sure! What topic should the presentation be about, and roughly how many slides do you want?"),
    (["write some code", "write a program", "code something for me"], "Happy to! What should the program do, and which language would you like (for example Python, JavaScript or C++)?"),
    (["draw something", "make an image", "generate a picture"], "Sure! What would you like in the picture? You can also tell me a style, like photo, anime, watercolor or 3D."),
    (["find a place", "search for a shop"], "What kind of place are you looking for, and near where? For example: \"cafés near me\" or \"pharmacies in Anna Nagar\"."),
    (["directions please", "how do I get there"], "Where would you like to go, and where are you starting from? I can give driving, walking or cycling directions."),
    (["make a document", "write a report"], "What's the topic, and do you want it as a PDF or a Word document?"),
]

MORE_UNSUPPORTED = [
    (["post this on instagram for me", "upload my photo to facebook"], "I can't post to social media from here. I can help you write a great caption though. What's the photo about?"),
    (["order a pizza for me", "book a cab to the airport"], "I can't place orders or bookings. I can find nearby options and their phone numbers or map links so you can book quickly. Want me to do that?"),
    (["turn on my wifi", "increase my phone volume"], "I can't change your phone's settings. You can do it from the quick settings panel: swipe down from the top of the screen."),
    (["read my messages", "check my whatsapp"], "I can't access your messages or other apps on your phone. If you paste the text here, I can help you summarise it or write a reply."),
]
