"""More hand-written code tasks. Each program is checked by
training/check_code.py (run / compile) before it's used for training."""

MORE_CODE_TASKS = [
    {"asks": ["Write a Python script that generates a strong random password", "password generator in python", "Make me a Python password generator"],
     "filename": "password.py", "desc": "Generates strong random passwords",
     "content": "import secrets\nimport string\nimport sys\n\n\ndef make_password(length=16):\n    chars = string.ascii_letters + string.digits + \"!@#$%^&*-_\"\n    while True:\n        pw = \"\".join(secrets.choice(chars) for _ in range(length))\n        if (any(c.islower() for c in pw) and any(c.isupper() for c in pw)\n                and any(c.isdigit() for c in pw)):\n            return pw\n\n\nif __name__ == \"__main__\":\n    length = int(sys.argv[1]) if len(sys.argv) > 1 else 16\n    print(make_password(length))\n",
     "explain": "Run `python password.py` for a 16-character password, or `python password.py 24` for a longer one. It uses the `secrets` module, which is safe for passwords."},
    {"asks": ["Write a Python script that fetches a web page title", "python get the title of a website", "Python program to print a page's title"],
     "filename": "page_title.py", "desc": "Prints the <title> of a web page",
     "content": "import re\nimport sys\nfrom urllib.request import Request, urlopen\n\n\ndef page_title(url):\n    req = Request(url, headers={\"User-Agent\": \"Mozilla/5.0\"})\n    html = urlopen(req, timeout=10).read().decode(\"utf-8\", \"replace\")\n    match = re.search(r\"<title[^>]*>(.*?)</title>\", html, re.I | re.S)\n    return match.group(1).strip() if match else \"(no title)\"\n\n\nif __name__ == \"__main__\":\n    print(page_title(sys.argv[1] if len(sys.argv) > 1 else \"https://example.com\"))\n",
     "explain": "Run `python page_title.py https://example.com`. It only uses Python's standard library."},
    {"asks": ["Write a Python class for a bank account", "bank account class in python with deposit and withdraw", "Python OOP example: bank account"],
     "filename": "bank_account.py", "desc": "A BankAccount class with deposits, withdrawals and history",
     "content": "class BankAccount:\n    def __init__(self, owner, balance=0.0):\n        self.owner = owner\n        self.balance = balance\n        self.history = []\n\n    def deposit(self, amount):\n        if amount <= 0:\n            raise ValueError(\"Deposit must be positive\")\n        self.balance += amount\n        self.history.append((\"deposit\", amount))\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            raise ValueError(\"Insufficient funds\")\n        self.balance -= amount\n        self.history.append((\"withdraw\", amount))\n\n\nif __name__ == \"__main__\":\n    acct = BankAccount(\"Asha\", 100)\n    acct.deposit(50)\n    acct.withdraw(30)\n    print(acct.owner, acct.balance, acct.history)\n",
     "explain": "It raises an error for invalid deposits or overdrafts. Running the file prints a short demo: `Asha 120 [...]`."},
    {"asks": ["Write a Python quiz game", "make a simple quiz in python", "Python multiple choice quiz program"],
     "filename": "quiz.py", "desc": "A small multiple-choice quiz game",
     "content": "QUESTIONS = [\n    (\"What is the capital of Japan?\", [\"Seoul\", \"Tokyo\", \"Beijing\"], 1),\n    (\"How many planets are in the solar system?\", [\"8\", \"9\", \"7\"], 0),\n    (\"Which gas do plants absorb?\", [\"Oxygen\", \"Nitrogen\", \"Carbon dioxide\"], 2),\n]\n\nscore = 0\nfor question, options, answer in QUESTIONS:\n    print(\"\\n\" + question)\n    for i, option in enumerate(options, 1):\n        print(f\"  {i}. {option}\")\n    choice = input(\"Your answer: \").strip()\n    if choice == str(answer + 1):\n        print(\"Correct!\")\n        score += 1\n    else:\n        print(f\"Wrong, it was {options[answer]}.\")\nprint(f\"\\nYou scored {score}/{len(QUESTIONS)}\")\n",
     "explain": "Run `python quiz.py`. Add your own questions to the `QUESTIONS` list: question, options, and the index of the right answer."},
    {"asks": ["Write a JavaScript function to shuffle an array", "js shuffle array", "Fisher-Yates shuffle in JavaScript"],
     "filename": "shuffle.js", "desc": "An unbiased array shuffle (Fisher–Yates)",
     "content": "// Shuffles a copy of the array using the Fisher-Yates algorithm.\nfunction shuffle(items) {\n  const a = [...items];\n  for (let i = a.length - 1; i > 0; i--) {\n    const j = Math.floor(Math.random() * (i + 1));\n    [a[i], a[j]] = [a[j], a[i]];\n  }\n  return a;\n}\n\nconsole.log(shuffle([1, 2, 3, 4, 5]));\n",
     "explain": "Run `node shuffle.js`. It returns a new shuffled array and leaves the original unchanged."},
    {"asks": ["Make a tip calculator web page", "html tip calculator", "Build a tip calculator in HTML and JavaScript"],
     "filename": "tip.html", "desc": "A tip and bill-splitting calculator",
     "content": "<!doctype html>\n<html>\n<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Tip calculator</title>\n<style>body{font-family:system-ui;max-width:360px;margin:40px auto;padding:0 16px}label{display:block;margin:12px 0 4px}input{width:100%;padding:8px;font-size:16px}#out{margin-top:20px;font-size:20px;font-weight:600}</style></head>\n<body>\n<h1>Tip calculator</h1>\n<label>Bill<input id=\"bill\" type=\"number\" value=\"1000\"></label>\n<label>Tip %<input id=\"tip\" type=\"number\" value=\"10\"></label>\n<label>People<input id=\"people\" type=\"number\" value=\"2\" min=\"1\"></label>\n<div id=\"out\"></div>\n<script>\nfunction calc() {\n  const bill = +document.getElementById(\"bill\").value;\n  const tip = +document.getElementById(\"tip\").value;\n  const people = Math.max(1, +document.getElementById(\"people\").value);\n  const total = bill * (1 + tip / 100);\n  document.getElementById(\"out\").textContent = `Total ${total.toFixed(2)} · ${(total / people).toFixed(2)} each`;\n}\ndocument.querySelectorAll(\"input\").forEach(i => i.addEventListener(\"input\", calc));\ncalc();\n</script>\n</body>\n</html>\n",
     "explain": "Open it in a browser. The total and per-person amount update as you type."},
    {"asks": ["Write a C program to check if a number is prime", "prime checker in c", "C code: is this number prime?"],
     "filename": "prime.c", "desc": "Checks whether a number is prime",
     "content": "#include <stdio.h>\n\nint is_prime(long n) {\n    if (n < 2) return 0;\n    for (long d = 2; d * d <= n; d++) {\n        if (n % d == 0) return 0;\n    }\n    return 1;\n}\n\nint main(void) {\n    long n;\n    printf(\"Enter a number: \");\n    if (scanf(\"%ld\", &n) != 1) return 1;\n    printf(\"%ld is %s\\n\", n, is_prime(n) ? \"prime\" : \"not prime\");\n    return 0;\n}\n",
     "explain": "Compile with `gcc prime.c -o prime` and run `./prime`. It only checks divisors up to the square root, so it's fast."},
    {"asks": ["Write a C++ program for a simple calculator", "c++ calculator program", "Calculator in C++ with + - * /"],
     "filename": "calculator.cpp", "desc": "A command-line calculator for + − × ÷",
     "content": "#include <iostream>\n\nint main() {\n    double a, b;\n    char op;\n    std::cout << \"Enter an expression (e.g. 6 * 7): \";\n    if (!(std::cin >> a >> op >> b)) return 1;\n    switch (op) {\n        case '+': std::cout << a + b << '\\n'; break;\n        case '-': std::cout << a - b << '\\n'; break;\n        case '*': std::cout << a * b << '\\n'; break;\n        case '/':\n            if (b == 0) std::cout << \"Can't divide by zero\\n\";\n            else std::cout << a / b << '\\n';\n            break;\n        default: std::cout << \"Unknown operator\\n\";\n    }\n    return 0;\n}\n",
     "explain": "Compile with `g++ calculator.cpp -o calculator`, run it and type something like `6 * 7`."},
    {"asks": ["Write a bash script that shows disk usage of the biggest folders", "bash script to find large folders", "Shell script: top 10 biggest directories"],
     "filename": "biggest.sh", "desc": "Lists the biggest folders under a path",
     "content": "#!/usr/bin/env bash\nset -euo pipefail\n\ntarget=\"${1:-.}\"\ndu -sh \"$target\"/* 2>/dev/null | sort -rh | head -n 10\n",
     "explain": "Run `bash biggest.sh ~/` to see the 10 biggest items in your home folder."},
    {"asks": ["Write SQL to create a students table and query the top scorers", "sql for students table", "SQL example with a students table"],
     "filename": "students.sql", "desc": "Creates a students table, adds data and finds the top scorers",
     "content": "CREATE TABLE students (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  grade INTEGER NOT NULL,\n  score REAL NOT NULL\n);\n\nINSERT INTO students (name, grade, score) VALUES\n  ('Asha', 10, 92.5),\n  ('Ben', 10, 78.0),\n  ('Chen', 11, 88.0),\n  ('Divya', 11, 95.5),\n  ('Eli', 10, 84.0);\n\n-- Top 3 students overall\nSELECT name, grade, score FROM students ORDER BY score DESC LIMIT 3;\n\n-- Average score per grade\nSELECT grade, ROUND(AVG(score), 1) AS average FROM students GROUP BY grade;\n",
     "explain": "It works in SQLite, PostgreSQL and MySQL. Try it with `sqlite3 school.db < students.sql`."},
    {"asks": ["Make a CSS loading spinner", "css spinner animation", "Create a loading animation with CSS"],
     "filename": "spinner.html", "desc": "A pure-CSS loading spinner",
     "content": "<!doctype html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<style>\nbody{display:grid;place-items:center;height:100vh;margin:0;background:#0f1221}\n.spinner{width:56px;height:56px;border:6px solid rgba(255,255,255,.15);border-top-color:#8b7cff;border-radius:50%;animation:spin 0.9s linear infinite}\n@keyframes spin{to{transform:rotate(360deg)}}\n</style>\n</head>\n<body><div class=\"spinner\" role=\"status\" aria-label=\"Loading\"></div></body>\n</html>\n",
     "explain": "Open it in a browser. Change `#8b7cff` for a different color or the `0.9s` for speed."},
    {"asks": ["Write a Python script to convert a CSV file to JSON", "csv to json converter python", "Convert CSV into JSON with Python"],
     "filename": "csv_to_json.py", "desc": "Converts a CSV file into a JSON array",
     "content": "import csv\nimport json\nimport sys\n\nif len(sys.argv) != 3:\n    sys.exit(\"Usage: python csv_to_json.py input.csv output.json\")\n\nwith open(sys.argv[1], newline=\"\", encoding=\"utf-8\") as f:\n    rows = list(csv.DictReader(f))\n\nwith open(sys.argv[2], \"w\", encoding=\"utf-8\") as f:\n    json.dump(rows, f, indent=2, ensure_ascii=False)\n\nprint(f\"Converted {len(rows)} rows\")\n",
     "explain": "Run `python csv_to_json.py data.csv data.json`. The first row of the CSV becomes the JSON keys."},
    {"asks": ["Write a Python number guessing game", "guess the number game python", "Make a number guessing game"],
     "filename": "guess.py", "desc": "A guess-the-number game",
     "content": "import random\n\nsecret = random.randint(1, 100)\ntries = 0\nprint(\"I'm thinking of a number between 1 and 100.\")\nwhile True:\n    try:\n        guess = int(input(\"Your guess: \"))\n    except ValueError:\n        print(\"Please type a number.\")\n        continue\n    tries += 1\n    if guess < secret:\n        print(\"Higher!\")\n    elif guess > secret:\n        print(\"Lower!\")\n    else:\n        print(f\"Correct! You got it in {tries} tries.\")\n        break\n",
     "explain": "Run `python guess.py` and follow the hints."},
    {"asks": ["Write a Node.js HTTP server", "simple web server in node", "Make a basic Node server that returns JSON"],
     "filename": "server.js", "desc": "A minimal Node.js HTTP server",
     "content": "const http = require(\"http\");\n\nconst server = http.createServer((req, res) => {\n  if (req.url === \"/api/hello\") {\n    res.writeHead(200, { \"Content-Type\": \"application/json\" });\n    res.end(JSON.stringify({ message: \"Hello from Node!\" }));\n  } else {\n    res.writeHead(200, { \"Content-Type\": \"text/plain\" });\n    res.end(\"Server is running. Try /api/hello\\n\");\n  }\n});\n\nserver.listen(3000, () => console.log(\"Listening on http://localhost:3000\"));\n",
     "explain": "Run `node server.js` and open http://localhost:3000/api/hello."},
    {"asks": ["Make a YAML config for a GitHub Actions Python CI", "github actions workflow for python tests", "CI workflow yaml for pytest"],
     "filename": "ci.yml", "desc": "A GitHub Actions workflow that runs pytest",
     "content": "name: CI\n\non:\n  push:\n  pull_request:\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: \"3.12\"\n      - run: pip install -r requirements.txt\n      - run: pytest -q\n",
     "explain": "Save it as `.github/workflows/ci.yml` in your repo. It runs your tests on every push and pull request."},
    {"asks": ["Write a Lua function to reverse a table", "reverse a list in lua", "Lua table reverse"],
     "filename": "reverse.lua", "desc": "Reverses a Lua table (array)",
     "content": "local function reverse(t)\n  local out = {}\n  for i = #t, 1, -1 do\n    out[#out + 1] = t[i]\n  end\n  return out\nend\n\nprint(table.concat(reverse({1, 2, 3, 4, 5}), \", \"))\n",
     "explain": "Run `lua reverse.lua`. It prints `5, 4, 3, 2, 1`."},
]
MORE_HELD_OUT_CODE_TASKS = [
    {"asks": ["Write a Python script that checks if a year is a leap year", "leap year checker in python"],
     "filename": "leap_year.py", "desc": "Checks whether a year is a leap year",
     "content": "def is_leap(year):\n    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)\n\n\nyear = int(input(\"Year: \"))\nprint(f\"{year} is {'a leap year' if is_leap(year) else 'not a leap year'}\")\n",
     "explain": "Run `python leap_year.py` and type a year."},
    {"asks": ["Write a C program that counts vowels in a sentence", "count vowels in c"],
     "filename": "vowels.c", "desc": "Counts the vowels in a line of text",
     "content": "#include <ctype.h>\n#include <stdio.h>\n\nint main(void) {\n    char line[1024];\n    int count = 0;\n    if (!fgets(line, sizeof line, stdin)) return 1;\n    for (char *p = line; *p; p++) {\n        char c = (char)tolower((unsigned char)*p);\n        if (c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u') count++;\n    }\n    printf(\"Vowels: %d\\n\", count);\n    return 0;\n}\n",
     "explain": "Compile with `gcc vowels.c -o vowels` and type a sentence."},
]
